### ISSUE TITLE
How can I download thousands of tweets without hitting the API limits?

### ISSUE THREAD

**Issue by lumenwrites** [PLhery/node-twitter-api-v2#129]
Hi there! My goal is to be able to download all the tweets from a single account. The problem is that some of the accounts I'm interested in have tens of thousands of tweets. I have an elevated developer account (not academic), and it seems like my limits are 900 tweets per 15 minutes.

How can I avoid hitting those limits?

I have tried a simple solution of just waiting 1.2 seconds between fetching each tweet:
```javascript
const timer = ms => new Promise(res => setTimeout(res, ms))

async function fetchTweets(username) {
  const timeline = await client.v1.userTimelineByUsername(username, {
    include_entities: true,
    exclude_replies: true,
  })
  for await (const tweet of timeline) {
    saveTweet(tweet, `./twitter/out/${username}-tweets.json`)
    await timer(1200) // wait 1.2 seconds between fetching tweets.
    console.log(`Fetched ${count} tweets. Remaining: ${timeline.rateLimit.remaining}`)
  }
}
```

But it doesn't seem to work, the script just quits after about 900 tweets, not sure why.

**Comment by alkihis** [comment]
Hi :)

You **can't** save all tweets of someone. `userTimelineByUsername` returns a maximum of 3200 tweets (see [here](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline)), **without any filter**. Here's, you choose to exclude replies, so it can decrease this count to around 900.

Limits are not 900 tweets/15 minutes, it is 900 API calls by 15 minutes. You didn't set the `count` parameter, so the default (20, if I remember well) is used.
So you can, with this code, get a maximum of 900*20 = 18000 tweets per 15 minutes (*theorically*).

Even if this limit is not hit, you cannot go further in time. Twitter forbid it by setting this arbitary 3200 tweets limit.

If this is for **your** account, you can your archive, that contains usable JSON files with all your tweets.
If this is for another account, unfortunately, there is no public method to fetch all tweets of a single account.

**Comment by lumenwrites** [comment]
Ah, that's really unfortunate.

Can you then help me to figure out how can I fetch as many tweets as possible?

Running this code:
```javascript
async function fetchTweets(username) {
  const timeline = await client.v1.userTimelineByUsername(username, {
    include_entities: true,
    exclude_replies: true,
    trim_user: true,
    count: 3200
  })
  console.log(timeline.tweets.length)
}
```

Gives me only 73 tweets for some reason.

**Comment by alkihis** [comment]
Please read the Twitter documentation before asking a question :sweat_smile: 
`count` is 200 maximum: [here](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline).
You ask for 200, it excludes replies (remember, `count` filter is applied BEFORE filtering replies), you can totally end up to getting 73 tweets. Use the async iterator or calls to `.next()` / `.fetchNext()` / `.fetchLast()` to get all that you can obtain.

For your next questions, can you please use the Discussion feature instead of opening an issue? 
An issue is meant to be used when you encounter a problem *inherent to the library*, not with the Twitter API itself. 
Note that [here, there's a Twitter dev forum](https://twittercommunity.com/) if you want to ask questions with the API.

Thank you!

**Comment by lumenwrites** [comment]
Oh, ok, I understand, sorry!

Thank you very much for your help!
