### ISSUE TITLE
Refresh tokens automatically

### ISSUE THREAD

**Issue by sleeyax** [PLhery/node-twitter-api-v2#248]
**Is your feature request related to a problem? Please describe.**
I have a user access token and a refresh token to access the Twitter V2 API. At the moment I need to manually refresh those tokens in time when they expire, otherwise I get a `401 Unauthorized` response.

**Describe the solution you'd like**
Either expose an API that exposes functionality to automatically refresh the tokens when necessary or provide an interface so developers can write a plugin to do this.

**Describe alternatives you've considered**
I could wrap every method call in a helper method to catch errors, refresh tokens and retry but that's kinda ugly and feels like a hack. 

**Additional context**
/

**Comment by nolbuzanis** [comment]
@PLhery You can assign this one to me if you like

**Comment by alkihis** [comment]
Hi,
Problem here is that we cannot safely say *when* a token is expired of not before making a request.
*And* requests can be made concurrently, and we should not refresh a token multiple times.

So the logic solution should be:
At the first failed request, we ask for a new token, wait then we made the request again. 

Problems:
- If other requests fails in the same time? Should be throttle them? How?
- It suggests that we should handle the error by ourselves, but catching the error (and possibly re-emit it) alters the stack trace in JavaScript
- If token refresh fails, what should we throw? Original error or refresh error? For both solutions, this isn't optimal, because some data will be lost. Changing error signature by adding two errors in one is not a solution neither
- We need some storage to keep `refreshToken` in instance, because we cannot refresh a token with `accessToken` only
- When the token is refresh, we should highly except a way to get and store it automatically (in a DB/memory) for further usage. That suggests usage of callbacks given to client instance. It can be thought plugins, but it isn't optimal

All of that suggests that, **no**, refreshing token automatically will not part of `twitter-api-v2` yet.
A plugin API can be implemented for allowing returning a custom value upon request error, that isn't possible yet (and i'm not fan of it neither, because this will alter stack trace in every case).

**Comment by alkihis** [comment]
I implemented a test plugin within this branch: https://github.com/PLhery/node-twitter-api-v2/blob/test/refresh-token-plugin-api/src/plugins/token.auto.refresh.plugin.ts

This come with some limitations, most of them comes to error stack trace that can be re-written.

This handles:
- Concurrency requests, only one request for refreshing token can be made at a time
- Recursive requests, if token is refreshed but the retry fail with 401 too, it will directly throw
- Storage of credentials+refreshToken within plugin
- Callback for token refreshing

But it isn't perfect 🤷

**Comment by sartoshi-foot-dao** [comment]
Thanks @alkihis

Excellent maintainer!

**Comment by alkihis** [comment]
It's me again.

1.12.0 is out and this new plugin is now available: [@twitter-api-v2/plugin-token-refresher](https://www.npmjs.com/package/@twitter-api-v2/plugin-token-refresher)

Tells me if it fits your needs!

**Comment by sartoshi-foot-dao** [comment]
Will test later. Thanks again @alkihis
