### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by itisshadow** [PLhery/node-twitter-api-v2#379]
**Describe the bug**
When using tweet.reply() method I sometimes get the error URI malformed.

**To Reproduce**
![image](https://user-images.githubusercontent.com/63856100/192561679-622a2d8a-c972-4238-af1f-fc3bf7e99a78.png)
![image](https://user-images.githubusercontent.com/63856100/192561839-aa641c94-7fca-46f6-8856-a9e86825e3eb.png)

**Expected behavior**
Expected behaviour is that the bot should reply to the user's tweet with the exact same text, but "uwuified".
![image](https://user-images.githubusercontent.com/63856100/192562122-bb0ac6bb-77c4-447f-9507-549d42f7bbe3.png)

**Version**
 - Node.js version 16.15.0
 - Lib version 1.12.5
 - OS Ubuntu Server 18.04.6 LTS

**Additional context**

**Comment by itisshadow** [comment]
Heyya, I've been busy with Uni today but I can create one for you over the weekend^^

**Comment by alkihis** [comment]
Hi, I come back on this before you make anything!

I might be caused by this line of code:
![image](https://user-images.githubusercontent.com/32335180/193245557-db1a4546-ed75-499f-ae79-8e65c4711fe6.png)

When you substring a thing in JS, indexes specifies UTF-16 characters, not real characters.
If you slice a string on two completing code points (like in the middle of `🏳️‍🌈` character, which have 4 code points), your string becomes invalid and unconvertible.

It is a really good chance that you should slice your string "better" using graphene splitting instead of `.slice/.substring` before giving it to the library.

**Comment by itisshadow** [comment]
I'll give it a shot and see whether this works. What I'm wondering is if each codepoint counts as a character to the twitter api, or each actual character counts, because the reason I need this is to avoid the error that the tweet is too long
