### ISSUE TITLE
[bug] JavaScript's floating point inaccuracy makes IDs invalid

### ISSUE THREAD

**Issue by NyCodeGHG** [PLhery/node-twitter-api-v2#400]
**Describe the bug**
Due to the nature of javascripts number type being a floating point number, IDs can be inaccurate and randomly turn into another number.

**To Reproduce**
Example with the following id: `1588987262754234368`
Open your Browser's console or the node repl and paste the number.

![image](https://user-images.githubusercontent.com/37078297/200139298-a31e71f8-8c6b-4f39-947d-b49053ee60a9.png)
js screws up the number because of floating point inaccuracy

**Expected behavior**
A number should stay the same. I would suggest using either just a string for the id or BigInt.

**Version**
 - Node.js version: 16.18.0
 - Lib version: 1.12.9
 - OS: Windows

**Additional context**
This would be a breaking change

**Comment by camiaei** [comment]
hi. I'm pretty sure ids are string. could you double check?On Nov 5, 2022 17:17, Marie Ramlow ***@***.***> wrote:
Describe the bug
Due to the nature of javascripts number type being a floating point number, IDs can be inaccurate and randomly turn into another number.
To Reproduce
Create a new Tweet and hope Snowflake generation generates a tweet with an id which is too big for javascript.
Expected behavior
A clear and concise description of what you expected to happen.
A number should stay the same. I would suggest using either just a string for the id or BigInt.
Version
Node.js version: 16.18.0Lib version: 1.12.9OS: Windows
Additional context
This would be a breaking change

**Comment by NyCodeGHG** [comment]
I should have said that I'm using API v1.
[here](https://github.com/PLhery/node-twitter-api-v2/blob/dc39119c3a0085be348b125874428da71d048888/src/types/v1/tweet.v1.types.ts#L10) in the TweetV1 type id is a number. If IDs are strings in v2 I could switch to that

**Comment by camiaei** [comment]
I didn't know that in v1 they were numbers
Maybe this can help you

![image](https://user-images.githubusercontent.com/79164595/200141048-231058d1-b1fa-4cd9-870f-0d3c0a67b35e.png)
https://developer.twitter.com/en/docs/twitter-ids
https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet

**Comment by NyCodeGHG** [comment]
oh maybe i should have looked a bit more into my autocomplete, i'll just use id_str. thank you :)
