### ISSUE TITLE
Login with id:pass

### ISSUE THREAD

**Issue by janyesilyurt** [PLhery/node-twitter-api-v2#69]
Hello bro, I couldn't understand much when I studied the document because I'm just starting to learn Nodejs. I can get tokens in php with twitter username and password, can you teach me how to get it in nodejs?

**Comment by alkihis** [comment]
Hello,
Which endpoints do you want to use?

Authentification method vary between endpoints. 
Entreprise endpoints use id+password. You can create a client with those [here](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/auth.md#basic-authentification-flow). **Note: you cannot use regular endpoints with those kind of auth**.

Otherwise, you **must** setup a login flow to obtain user tokens [see here](https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter) [or with an example here](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/examples.md#auth-flow).
